project_name: compass
release:
  prerelease: auto
before:
  hooks:
    - go mod tidy
    - make clean
builds:
  - id: compass
    main: ./main.go
    binary: compass
    flags: [-a]
    ldflags:
      - -X github.com/goto/compass/cli.Version={{.Tag}}
      - -X github.com/goto/compass/cli.BuildCommit={{.FullCommit}}
      - -X github.com/goto/compass/cli.BuildDate={{.Date}}
    goos: [linux, darwin, windows]
    goarch: [amd64, 386, arm, arm64] # skip goarch 386 and arm due to conflicts with "github.com/blastrain/vitess-sqlparser" library
    env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "darwin" }}macos
      {{- else if eq .Arch "linux" }}linux
      {{- else if eq .Arch "windows" }}windows
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - compass
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/gotocompany/{{.ProjectName}}:latest"
      - "docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}-amd64"
nfpms:
  - maintainer: gotocompany
    description: Metadata Discovery and Lineage Service
    homepage: https://github.com/goto/compass
    license: Apache 2.0
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "darwin" }}macos{{- else }}{{ .Arch }}{{ end }}
scoop:
  bucket:
    owner: goto
    name: scoop-bucket
  homepage: "https://github.com/goto/compass"
  description: "Metadata Discovery and Lineage Service"
  license: Apache 2.0
brews:
  - name: compass
    homepage: "https://github.com/goto/compass"
    description: "Metadata Discovery and Lineage Service"
    tap:
      owner: goto
      name: homebrew-tap
    license: "Apache 2.0"
    folder: Formula

    dependencies:
      - name: git
    install: |-
      bin.install "compass"
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com
