// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	asset "github.com/goto/compass/core/asset"

	mock "github.com/stretchr/testify/mock"
)

// LineageParserClient is an autogenerated mock type for the LineageParserClient type
type LineageParserClient struct {
	mock.Mock
}

type LineageParserClient_Expecter struct {
	mock *mock.Mock
}

func (_m *LineageParserClient) EXPECT() *LineageParserClient_Expecter {
	return &LineageParserClient_Expecter{mock: &_m.Mock}
}

// FetchColumnLineage provides a mock function with given fields: ctx, query
func (_m *LineageParserClient) FetchColumnLineage(ctx context.Context, query string) (asset.LineageGraph, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for FetchColumnLineage")
	}

	var r0 asset.LineageGraph
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (asset.LineageGraph, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) asset.LineageGraph); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(asset.LineageGraph)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LineageParserClient_FetchColumnLineage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchColumnLineage'
type LineageParserClient_FetchColumnLineage_Call struct {
	*mock.Call
}

// FetchColumnLineage is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *LineageParserClient_Expecter) FetchColumnLineage(ctx interface{}, query interface{}) *LineageParserClient_FetchColumnLineage_Call {
	return &LineageParserClient_FetchColumnLineage_Call{Call: _e.mock.On("FetchColumnLineage", ctx, query)}
}

func (_c *LineageParserClient_FetchColumnLineage_Call) Run(run func(ctx context.Context, query string)) *LineageParserClient_FetchColumnLineage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LineageParserClient_FetchColumnLineage_Call) Return(_a0 asset.LineageGraph, _a1 error) *LineageParserClient_FetchColumnLineage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LineageParserClient_FetchColumnLineage_Call) RunAndReturn(run func(context.Context, string) (asset.LineageGraph, error)) *LineageParserClient_FetchColumnLineage_Call {
	_c.Call.Return(run)
	return _c
}

// NewLineageParserClient creates a new instance of LineageParserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLineageParserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *LineageParserClient {
	mock := &LineageParserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
